Add samples

diff --git a/redpen-server/bin/redpen-server b/redpen-server/bin/redpen-server
--- a/redpen-server/bin/redpen-server
+++ b/redpen-server/bin/redpen-server
@@ -19,24 +19,28 @@ done
 # Find RedPen home
 REDPEN_HOME=`dirname "$SCRIPT"`/..
 
+#####################################################
 #
 # Configurations
 #
+#####################################################
 
 # When this key is registered RedPen server is able to by http access.
 # If you do not want such behavior, please comment out STOP_KEY.
 STOP_KEY=redpen.stop
 
-# Port number for redpen server
+# Port number for RedPen server
 REDPEN_PORT=8080
 
-# RedPen log
+# RedPen log file
 REDPEN_LOG_DIR=$REDPEN_HOME/logs
 REDPEN_LOG_FILE=$REDPEN_LOG_DIR/redpen.log
 
+#####################################################
 #
 # Main procedure
 #
+#####################################################
 
 # set command
 COMMAND=start
@@ -49,7 +53,7 @@ REDPEN_WAR_FILE="bin/redpen-server.war"
 JAVA_CMD="$JAVA_HOME/bin/java"
 
 if [ ! -x "$JAVA_CMD" ]; then
-    echo "Error: $JAVA_CMD is not execututable. Can not start RedPen" 1>&2
+    echo "Error: $JAVA_CMD is not executable. Can not start RedPen" 1>&2
     exit 1
 fi
 
@@ -63,15 +67,15 @@ fi
 
 if [ $COMMAND = "start" ]; then
     if [ -n "$STOP_KEY" ]; then
-        echo "starting redpen with stop key..." 1>&2
+        echo "starting RedPen server with stop key..." 1>&2
         exec "$JAVA_CMD" -jar $JAVA_OPTS $REDPEN_WAR_FILE -p $REDPEN_PORT -STOP_KEY $STOP_KEY 2&>1 2>> $REDPEN_LOG_FILE &
         exit 0
     fi
-    echo "starting redpen without stop key..." 1>&2
+    echo "starting RedPen server without stop key..." 1>&2
     exec "$JAVA_CMD" -jar $JAVA_OPTS $REDPEN_WAR_FILE -p $REDPEN_PORT 2&>1 2>> $REDPEN_LOG_FILE &
     exit 0
 elif [ $COMMAND = "stop" ]; then
-    echo "stopping redpen server" 1>&2
+    echo "stopping RedPen server" 1>&2
     curl -d "token=redpen.stop" http://localhost:$REDPEN_PORT/shutdown 2&>1 2>> $REDPEN_LOG_FILE
     exit 0
 else
