Specify log dir

diff --git a/redpen-server/bin/redpen-server b/redpen-server/bin/redpen-server
--- a/redpen-server/bin/redpen-server
+++ b/redpen-server/bin/redpen-server
@@ -3,21 +3,6 @@
 ## RedPen Server startup script
 ##
 
-#
-# Configurations
-#
-
-# When this key is registered RedPen server is able to by http access.
-# If you do not want such behavior, please comment out STOP_KEY.
-STOP_KEY=redpen.stop
-
-# Port number for redpen server
-REDPEN_PORT=8080
-
-#
-# Main procedure
-#
-
 # SCRIPT may be an arbitrarily deep series of symlinks. Loop until we have the concrete path.
 SCRIPT="$0"
 while [ -h "$SCRIPT" ] ; do
@@ -31,14 +16,33 @@ while [ -h "$SCRIPT" ] ; do
   fi
 done
 
+# Find RedPen home
+REDPEN_HOME=`dirname "$SCRIPT"`/..
+
+#
+# Configurations
+#
+
+# When this key is registered RedPen server is able to by http access.
+# If you do not want such behavior, please comment out STOP_KEY.
+STOP_KEY=redpen.stop
+
+# Port number for redpen server
+REDPEN_PORT=8080
+
+# RedPen log
+REDPEN_LOG_DIR=$REDPEN_HOME/logs
+REDPEN_LOG_FILE=$REDPEN_LOG_DIR/redpen.log
+
+#
+# Main procedure
+#
+
 # set command
 COMMAND=start
 if [ -n "$1" ]; then
   COMMAND=$1
 fi
-
-# Find RedPen home
-REDPEN_HOME=`dirname "$SCRIPT"`/..
 
 JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"
 REDPEN_WAR_FILE="bin/redpen-server.war"
@@ -49,15 +53,28 @@ if [ ! -x "$JAVA_CMD" ]; then
     exit 1
 fi
 
+if [ -e "$REDPEN_LOG_DIR" ]; then
+    echo "found log dir: $REDPEN_LOG_DIR" 1>&2
+else
+    echo "not found log dir: $REDPEN_LOG_DIR" 1>&2
+    echo "creating log dir: $REDPEN_LOG_DIR" 1>&2
+    mkdir $REDPEN_LOG_DIR
+fi
+
 if [ $COMMAND = "start" ]; then
     if [ -n "$STOP_KEY" ]; then
-	exec "$JAVA_CMD" -jar $JAVA_OPTS $REDPEN_WAR_FILE -p $REDPEN_PORT -STOP_KEY $STOP_KEY
+        echo "starting redpen with stop key..." 1>&2
+        exec "$JAVA_CMD" -jar $JAVA_OPTS $REDPEN_WAR_FILE -p $REDPEN_PORT -STOP_KEY $STOP_KEY 2&>1 2>> $REDPEN_LOG_FILE &
+	exit 0
     fi
-    exec "$JAVA_CMD" -jar $JAVA_OPTS $REDPEN_WAR_FILE -p $REDPEN_PORT
+    echo "starting redpen without stop key..." 1>&2
+    exec "$JAVA_CMD" -jar $JAVA_OPTS $REDPEN_WAR_FILE -p $REDPEN_PORT 2&>1 2>> $REDPEN_LOG_FILE &
+    exit 0
 elif [ $COMMAND = "stop" ]; then
     echo "stopping redpen server" 1>&2
-    curl -d "token=redpen.stop" http://localhost:$REDPEN_PORT/shutdown
+    curl -d "token=redpen.stop" http://localhost:$REDPEN_PORT/shutdown 2&>1 2>> $REDPEN_LOG_FILE
+    exit 0
 else
-    echo "Invalid command" 1>&2
+    echo "Invalid command: $COMMAND" 1>&2
     exit 1
 fi
